fix: capture exit code from npm view

diff --git a/lib/content/_job-release-integration.yml b/lib/content/_job-release-integration.yml
--- a/lib/content/_job-release-integration.yml
+++ b/lib/content/_job-release-integration.yml
@@ -3,10 +3,30 @@ defaults:
   run:
     shell: bash
 steps:
-  {{> stepGit }}
-  {{> stepNode }}
+  {{> stepNode lockfile=false }}
   - name: View in Registry
     run: |
-      name=$(cat package.json | jq -r .name) 
-      version="$\{{ fromJSON(needs.release.output.release).version }}"
-      npm view ${name}@${version}
+      EXIT_CODE=0
+
+      function is_published {
+        if npm view "$@" --loglevel=error > /dev/null; then
+          echo 0
+        else
+          echo 1
+        fi
+      }
+
+      for release in $(echo '$\{{ needs.release.outputs.releases }}' | jq -r '.[] | @base64'); do
+        name=$(echo "$release" | base64 --decode | jq -r .pkgName)
+        version=$(echo "$release" | base64 --decode | jq -r .version)
+        spec="$name@$version"
+        status=$(is_published "$spec")
+        if [[ "$status" -eq 1 ]]; then
+          echo "$spec ERROR"
+          EXIT_CODE=$status
+        else
+          echo "$spec OK"
+        fi
+      done
+
+      exit $EXIT_CODE
