feat: run reusable ci workflow on post dependabot

diff --git a/.github/actions/audit/action.yml b/.github/actions/audit/action.yml
--- a/.github/actions/audit/action.yml
+++ b/.github/actions/audit/action.yml
@@ -2,19 +2,24 @@
 
 name: Audit
 
-inputs:
-  shell:
-    description: shell to run on
-    default: bash
-
 runs:
   using: composite
   steps:
-    - name: Run Production Audit
-      shell: ${{ inputs.shell }}
-      run: |
-        npm audit --omit=dev
     - name: Run Full Audit
-      shell: ${{ inputs.shell }}
+      id: all
+      shell: bash
       run: |
-        npm audit --audit-level=none
+        if ! npm audit; then
+          COUNT=$(npm audit --audit-level=none --json | jq -r '.metadata.vulnerabilities.total')
+          echo "::warning title=All Vulnerabilities::Found $COUNT vulnerabilities"
+        fi
+
+    - name: Run Production Audit
+      id: production
+      shell: bash
+      run: |
+        if ! npm audit --omit=dev; then
+          COUNT=$(npm audit --omit=dev --audit-level=none --json | jq -r '.metadata.vulnerabilities.total')
+          echo "::error title=Production Vulnerabilities::Found $COUNT production vulnerabilities"
+          exit 1
+        fi
diff --git a/workspaces/content/lib/actions/audit.yml b/workspaces/content/lib/actions/audit.yml
--- a/workspaces/content/lib/actions/audit.yml
+++ b/workspaces/content/lib/actions/audit.yml
@@ -1,18 +1,23 @@
 name: Audit
 
-inputs:
-  shell:
-    description: shell to run on
-    default: {{ shell }}
-
 runs:
   using: composite
   steps:
-    - name: Run Production Audit
-      shell: $\{{ inputs.shell }}
-      run: |
-        {{ rootNpmPath }} audit --omit=dev
     - name: Run Full Audit
-      shell: $\{{ inputs.shell }}
+      id: all
+      shell: bash
       run: |
-        {{ rootNpmPath }} audit --audit-level=none
+        if ! {{ rootNpmPath }} audit; then
+          COUNT=$({{ rootNpmPath }} audit --audit-level=none --json | jq -r '.metadata.vulnerabilities.total')
+          echo "::warning title=All Vulnerabilities::Found $COUNT vulnerabilities"
+        fi
+
+    - name: Run Production Audit
+      id: production
+      shell: bash
+      run: |
+        if ! {{ rootNpmPath }} audit --omit=dev; then
+          COUNT=$({{ rootNpmPath }} audit --omit=dev --audit-level=none --json | jq -r '.metadata.vulnerabilities.total')
+          echo "::error title=Production Vulnerabilities::Found $COUNT production vulnerabilities"
+          exit 1
+        fi
