feat: rewrite to make it more extensible (#81)
BREAKING CHANGE: bin scripts are now `template-oss-apply` and
`template-oss-check`
renamed apply props `rootRepo`, `rootModule`,
`workspaceRepo`, `workspaceModule`

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -4,19 +4,45 @@ name: Pull Request Linting
 
 on:
   pull_request:
-    types: [opened, reopened, edited, synchronize]
+    types:
+      - opened
+      - reopened
+      - edited
+      - synchronize
 
 jobs:
   check:
     name: Check PR Title or Commits
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      - uses: actions/setup-node@v2
+      - name: Setup git user
+        run: |
+          git config --global user.email "ops+npm-cli@npmjs.com"
+          git config --global user.name "npm cli ops bot"
+      - uses: actions/setup-node@v3
         with:
-          node-version: '16'
+          node-version: 16.x
+      - name: Update to workable npm (windows)
+        # node 12 and 14 ship with npm@6, which is known to fail when updating itself in windows
+        if: matrix.platform.os == 'windows-latest' && (startsWith(matrix.node-version, '12') || startsWith(matrix.node-version, '14'))
+        run: |
+          curl -sO https://registry.npmjs.org/npm/-/npm-7.5.4.tgz
+          tar xf npm-7.5.4.tgz
+          cd package
+          node lib/npm.js install --no-fund --no-audit -g ..\npm-7.5.4.tgz
+          cd ..
+          rmdir /s /q package
+      - name: Update npm to 7
+        # If we do test on npm 10 it needs npm7
+        if: matrix.node-version <= 10
+        run: npm i --prefer-online --no-fund --no-audit -g npm@7
+      - name: Update npm to latest
+        if: matrix.node-version > 10
+        run: npm i --prefer-online --no-fund --no-audit -g npm@latest
+      - run: npm -v
       - name: Install deps
         run: |
           npm i -D @commitlint/cli @commitlint/config-conventional
@@ -24,4 +50,7 @@ jobs:
         env:
           PR_TITLE: ${{ github.event.pull_request.title }}
         run: |
-          npx commitlint -x @commitlint/config-conventional -V --from origin/main --to ${{ github.event.pull_request.head.sha }} || echo $PR_TITLE | npx commitlint -x @commitlint/config-conventional -V
+          npx commitlint -x @commitlint/config-conventional -V \
+            --from origin/main --to ${{ github.event.pull_request.head.sha }} \
+            || echo $PR_TITLE | \
+            npx commitlint -x @commitlint/config-conventional -V
